### ISSUE TITLE
Error bluepy

### ISSUE THREAD

**Issue by JELLY92** [BensonHsu/SBrick-Framework#6]
Hello,
I would like to write my program based on your code. I'm just learning and I've encountered a problem I can not deal with. Raspberry contacts Sbrick for a while and then I get this error:
```
Exception in thread channel_01:
Traceback (most recent call last):
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 274, in rcc_char_write_ex
    self._rcc_char.write(binary)
  File "/home/pi/SBrick-Framework-master/bluepy/btle.py", line 200, in write
    return self.peripheral.writeCharacteristic(self.valHandle, val, withResponse)
  File "/home/pi/SBrick-Framework-master/bluepy/btle.py", line 543, in writeCharacteristic
    return self._getResp('wr')
  File "/home/pi/SBrick-Framework-master/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/home/pi/SBrick-Framework-master/bluepy/btle.py", line 362, in _waitResp
    raise BTLEDisconnectError("Device disconnected", resp)
bluepy.btle.BTLEDisconnectError: Device disconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 58, in run
    self.drive()
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 62, in drive
    self.drive_channel()
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 94, in drive_channel
    self.exec_command(drive_hex_string)
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 106, in exec_command
    self._sbrick.rcc_char_write_ex(binary, reconnect_do_again=False)
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 283, in rcc_char_write_ex
    if BTLEException.DISCONNECTED == e.code:
AttributeError: type object 'BTLEException' has no attribute 'DISCONNECTED'

2019-08-02 12:26:14,292 [sbrick_m2mipc.py:92(DEBUG)] MainThread - Accept drive() event: {'direction': '00', 'exec_time': 10, 'channel': '01', 'power': 'FF', 'sbrick_id': '00:07:80:BD:15:F5'}
2019-08-02 12:26:14,295 [sbrick_api.py:104(DEBUG)] channel_01 - Exec command 010100FF
2019-08-02 12:26:14,295 [sbrick_api.py:266(DEBUG)] channel_01 - RCC characteristic writes binary: b'\x01\x01\x00\xff'
2019-08-02 12:26:14,296 [sbrick_api.py:282(ERROR)] channel_01 - SBrick (00:07:80:BD:15:F5): Helper not started (did you call connect()?)
Exception in thread channel_01:
Traceback (most recent call last):
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 274, in rcc_char_write_ex
    self._rcc_char.write(binary)
  File "/home/pi/SBrick-Framework-master/bluepy/btle.py", line 200, in write
    return self.peripheral.writeCharacteristic(self.valHandle, val, withResponse)
  File "/home/pi/SBrick-Framework-master/bluepy/btle.py", line 542, in writeCharacteristic
    self._writeCmd("%s %X %s\n" % (cmd, handle, binascii.b2a_hex(val).decode('utf-8')))
  File "/home/pi/SBrick-Framework-master/bluepy/btle.py", line 302, in _writeCmd
    raise BTLEInternalError("Helper not started (did you call connect()?)")
bluepy.btle.BTLEInternalError: Helper not started (did you call connect()?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 58, in run
    self.drive()
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 62, in drive
    self.drive_channel()
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 94, in drive_channel
    self.exec_command(drive_hex_string)
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 106, in exec_command
    self._sbrick.rcc_char_write_ex(binary, reconnect_do_again=False)
  File "/home/pi/SBrick-Framework-master/lib/sbrick_api.py", line 283, in rcc_char_write_ex
    if BTLEException.DISCONNECTED == e.code:
AttributeError: type object 'BTLEException' has no attribute 'DISCONNECTED'

2019-08-02 12:26:15,233 [sbrick_api.py:70(DEBUG)] timer_01 - Drive action times_up 010100FF
2019-08-02 12:26:24,294 [sbrick_api.py:70(DEBUG)] timer_01 - Drive action times_up 010100FF
^CReceive SIGINT signal
2019-08-02 12:28:27,814 [sbrick_m2mipc.py:39(INFO)] MainThread - Disconnect from mosquitto broker 127.0.0.1:1883
2019-08-02 12:28:27,816 [sbrick_api.py:221(INFO)] MainThread - Disconnect from SBrick(00:07:80:BD:15:F5) successfully
```

I use:
Raspberry Pi 3b+
Python 3.4
BlueZ 5.50
bluepy 1.3
pyuv 1.4
paho-mqtt 1.4

**Comment by tiagomiotto** [comment]
Hi there, this was caused by some exception catching code that was not properly written, I have fixed it in my fork https://github.com/tiagomiotto/SBrick-Framework but I'm still waiting on the pull request to this repo

**Comment by BensonHsu** [comment]
Hi,
This was caused from bluepy changes from v1.1.4 to v1.3.0.  There were some error handling object added in bluepy v1.3.0 such as "BTLEDisconnectError", "BTLEInternalError", "BTLEManagementError"... instead of v1.1.4 "INTERNAL_ERROR" "DISCONNECTED" defines which were in the "BTLEException" object.

Thanks to @tiagomiotto for this fix.

I also created a branch "bluepy_v1_1_4" for backward compatible.  If you use this branch, you should also use the correct bluepy version v1.1.4. Here are some commands of how to install bluepy v1.1.4:
```
pip3 uninstall bluepy
pip3 install bluepy==1.1.4
```
